

export const MCQ_REQUEST = 'MCQ_REQUEST';
export const MCQ_LOAD = 'MCQ_LOAD';
export const MCQ_FAIL    = 'MCQ_FAIL';
export const MCQ_ADD     = 'MCQ_ADD';
export const MCQ_EDIT     = 'MCQ_EDIT';
export const MCQ_SUBMIT_SOLUTION  = 'MCQ_SUBMIT_SOLUTION';
export const MCQ_GET_SOLUTION     = 'MCQ_GET_SOLUTION';
export const MCQ_DELETE  = 'MCQ_DELETE';
export const MCQ_DELETE_FAIL  = 'MCQ_DELETE_FAIL';
export const MCQ_UPDATE  = 'MCQ_UPDATE';
export const MCQ_CLEAR  = 'MCQ_CLEAR';

export const MCQ_LOAD_QUESTIONS  = 'MCQ_LOAD_QUESTIONS';
export const MCQ_LOAD_QUESTIONS_FAIL  = 'MCQ_LOAD_QUESTIONS_FAIL';
export const MCQ_LOAD_QUESTIONS_CLEAR  = 'MCQ_LOAD_QUESTIONS_CLEAR';


export const MCQ_TAKE_EXAM_REQUEST = 'MCQ_TAKE_EXAM_REQUEST'
export const MCQ_START_EXAM = 'MCQ_START_EXAM'
export const MCQ_UPDATE_EXAM = 'MCQ_UPDATE_EXAM'
export const MCQ_UPDATE_EXAM_STUDENT = 'MCQ_UPDATE_EXAM_STUDENT'
export const MCQ_SUBMIT_EXAM = 'MCQ_SUBMIT_EXAM'
export const MCQ_SUBMIT_STUDENT  = 'MCQ_SUBMIT_STUDENT';
export const MCQ_TAKE_CLEAR = 'MCQ_TAKE_CLEAR'
export const MCQ_TAKE_ERROR = 'MCQ_TAKE_ERROR'

export const MCQ_BYID_GET  = 'MCQ_BYID_GET';
export const MCQ_BYID_ERROR  = 'MCQ_BYID_ERROR';
export const MCQ_BYID_CLEAR  = 'MCQ_BYID_CLEAR';


export const MCQ_TEACHER_GET_SUBMISSIONS  = 'MCQ_TEACHER_GET_SUBMISSIONS';
export const MCQ_TEACHER_GET_SUBMISSIONS_ERROR  = 'MCQ_TEACHER_GET_SUBMISSIONS_ERROR';
export const MCQ_TEACHER_GET_SUBMISSIONS_CLEAR  = 'MCQ_TEACHER_GET_SUBMISSIONS_CLEAR';

export const MCQ_TEACHER_GET_SUBMISSIONSBYID  = 'MCQ_TEACHER_GET_SUBMISSIONSBYID';
export const MCQ_TEACHER_GET_SUBMISSIONSBYID_ERROR  = 'MCQ_TEACHER_GET_SUBMISSIONSBYID_ERROR';


export const MCQ_ADD_QUESTION     = 'MCQ_ADD_QUESTION';
export const MCQ_EDIT_QUESTION    = 'MCQ_EDIT_QUESTION';
export const MCQ_DELETE_QUESTION  = 'MCQ_DELETE_QUESTION';
export const MCQ_QUESTION_FAIL    = 'MCQ_QUESTION_FAIL';


export const MCQ_MANUAL_GRADE_QUESTION = 'MCQ_MANUAL_GRADE_QUESTION';
export const MCQ_MANUAL_GRADE_QUESTION_FAIL = 'MCQ_MANUAL_GRADE_QUESTION_FAIL';


export const MCQ_AUTOGRADE_EXAM = 'MCQ_AUTOGRADE_EXAM';
export const MCQ_AUTOGRADE_EXAM_FAIL = 'MCQ_AUTOGRADE_EXAM_FAIL';


export const MCQ_AUTOGRADE_ALL_EXAMS = 'MCQ_AUTOGRADE_ALL_EXAMS';
export const MCQ_AUTOGRADE_ALL_EXAMS_FAIL = 'MCQ_AUTOGRADE_ALL_EXAMS_FAIL';

export const MCQ_GET_ANALYTICS = 'MCQ_GET_ANALYTICS'
export const MCQ_GET_ANALYTICS_FAIL = 'MCQ_GET_ANALYTICS_FAIL'
export const MCQ_GET_ANALYTICS_CLEAR = 'MCQ_GET_ANALYTICS_FAIL'

export const MCQ_ADD_EQUATION     = 'MCQ_ADD_EQUATION';
export const MCQ_EDIT_EQUATION    = 'MCQ_EDIT_EQUATION';
export const MCQ_DELETE_EQUATION  = 'MCQ_DELETE_EQUATION';
export const MCQ_EQUATION_FAIL    = 'MCQ_EQUATION_FAIL';


export const CREATE_MCQ_TEMPLATE = 'CREATE_MCQ_TEMPLATE';
export const DELETE_MCQ_TEMPLATE = 'DELETE_MCQ_TEMPLATE';
