
export const LOAD_NOTEBOOK_LIST = 'LOAD_NOTEBOOK_LIST'
export const NOTEBOOK_LIST_FAIL = 'NOTEBOOK_LIST_FAIL'


export const ADD_NOTEBOOK    = 'ADD_NOTEBOOK'
export const DELETE_NOTEBOOK = 'DELETE_NOTEBOOK'

export const NOTEBOOK_ITEM_LIST   = 'NOTEBOOK_ITEM_LIST';
export const ADD_NOTEBOOK_ITEM    = 'ADD_NOTEBOOK_ITEM'
export const UPDATE_NOTEBOOK_ITEM = 'UPDATE_NOTEBOOK_ITEM'
export const DELETE_NOTEBOOK_ITEM = 'DELETE_NOTEBOOK_ITEM'
export const NOTEBOOK_ITEM_FAIL   = 'NOTEBOOK_ITEM_FAIL'
export const CLEAR_NOTEBOOK_ITEMS = 'CLEAR_NOTEBOOK_ITEMS'
export const LOAD_NOTEBOOK_DETAIL = 'LOAD_NOTEBOOK_DETAIL'
export const NOTEBOOK_DETAIL_FAIL = 'NOTEBOOK_DETAIL_FAIL'

export const UPDATE_NOTEBOOK_TITLE = 'UPDATE_NOTEBOOK_TITLE'
export const NOTEBOOK_TITLE_FAIL = 'NOTEBOOK_TITLE_FAIL'




export const UPDATE_SESSION_TITLE = 'UPDATE_SESSION_TITLE'
export const SESSION_TITLE_FAIL = 'SESSION_TITLE_FAIL'

export const CARD_LIST        = 'CARD_LIST';
export const ADD_CARD        = 'ADD_CARD';
export const CARDS_FAIL      = 'CARDS_FAIL';

export const UPDATE_CARD_TITLE = 'UPDATE_CARD_TITLE'
export const UPDATE_VIDEO_CARD  = 'UPDATE_VIDEO_CARD'

export const ADD_CARD_ITEM    = 'ADD_CARD_ITEM'
export const DELETE_CARD      = 'DELETE_CARD'
export const UPDATE_CARD_ITEM = 'UPDATE_CARD_ITEM'
export const DELETE_CARD_ITEM = 'DELETE_CARD_ITEM'

export const SESSION_VIEW_MODE = 'SESSION_VIEW_MODE'
export const CLEAR_SESSION = 'CLEAR_SESSION'
export const CLEAR_CARDS = 'CLEAR_CARDS'

export const ADD_QUESTION_TEST = 'ADD_QUESTION_TEST'